#pragma once
#include "Event.h"
#include "InputEvent.h"

enum GameEventType
{
    MOVE_EVENT = NUM_INPUT_EVENT_TYPES,
    MESSAGE_EVENT,
    QUIT_EVENT,
    SPAWN_EVENT,
    DESTROY_EVENT,
    DESTROY_ALL_EVENT,
    SWITCH_ANIMATION_EVENT,
    FREEZE_ANIMATION_EVENT,
    CONSUMING_EVENT,
    SCORE_EVENT,
    MENU_PLAY_EVENT,
    MENU_LOAD_EVENT,
    MENU_OPTIONS_EVENT,
    MENU_QUIT_EVENT,
    MENU_RESUME_EVENT,
    MENU_PAUSE_EVENT,
    MENU_DIFFICULTY_EVENT,
    MENU_QUIT_TO_MAIN_EVENT,
    MENU_SOUND_EVENT,
    MENU_MUSIC_EVENT,
    MENU_LANGUAGE_EVENT,
    WEB_FIRE_EVENT,
    WEB_HIT_EVENT,
    WEB_METER_EMPTY_EVENT,
    WEB_METER_REFILLED_EVENT,
    WEB_BLAST_EVENT,
    BLOCK_EVENT,
    BOSS_PHASE_EVENT,
    BOSS_DEAD_EVENT,
    BOSS_ATTACK_EVENT,
    COLLISION_EVENT,
    PUNCH_EVENT,
    NUM_GAME_EVENT_TYPES
};

class GameEvent :public Event
{
public:
	GameEvent(GameEventType type);
	virtual ~GameEvent();

private:
};